#!/usr/bin/env bash
# Generate a local .clangd for this project.
#
# Why: a single nvcc command spawns multiple host/device compilation jobs,
# which clangd cannot handle ("expected exactly one compiler job"). The
# generated config makes clangd parse CUDA with clang++ instead.
#
# The file contains machine-specific absolute paths and is gitignored;
# re-run this script on a new machine instead of editing it by hand.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

CUDA_PATH="${CUDA_PATH:-$(dirname "$(dirname "$(command -v nvcc)")")}"
CC="$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader 2>/dev/null | head -1 | tr -d ' .')"
CC="${CC:-80}"  # fallback arch for clangd parsing only

cat > "$ROOT/.clangd" <<EOF
# Generated by scripts/gen_clangd.sh — re-run the script instead of editing.
CompileFlags:
  Compiler: clang++
  Add:
    - -std=c++17
    - -xcuda
    - --cuda-path=$CUDA_PATH
    - --cuda-gpu-arch=sm_$CC
    - -I$ROOT/include
EOF

echo "wrote $ROOT/.clangd (cuda=$CUDA_PATH, arch=sm_$CC)"
